library/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('<int:book_id>', views.book_view, name='book_view'),
    path('new', views.book_create, name='book_new'),
    path('edit/<int:book_id>', views.book_update, name='book_edit'),
    path('delete/<int:book_id>', views.book_delete, name='book_delete'),
]

library/books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=64, default ="<no author>")
    pages = models.IntegerField()
    fiction_or_non = models.BooleanField()

    def __str__(self):
        return f"ID: {self.id} Title: {self.title}"

library/books/forms.py
from django.forms import ModelForm
from books.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'pages', 'fiction_or_non']

library/books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from books.models import Book
from books.forms import BookForm

# helper method function
def get_book(book_id):
    return Book.objects.get(id=book_id)

# route function
def book_list(request):
    books = Book.objects.all()
    data = {'all_books': books}
    return render(request, 'books/book_list.html', data)

def book_view(request, book_id):
    book = get_book(book_id)
    data = {'book': book}
    return render(request, 'books/book_detail.html', data)

def book_create(request):
    form = BookForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('books:book_list')
    return render(request, 'books/book_form.html', {'form': form, 'new_or_edit': 'New'})

    # if request.POST:
    #     try:
    #         book = Book()
    #         book.title = request.POST["title"]
    #         book.author = request.POST["author"]
    #         book.pages = request.POST["pages"]
    #         book.full_clean()
    #         book.save()
    #         return redirect('books:book_list')
    #     except:
    #         return HttpResponse("You encountered an error!")


    # return render(request, 'books/book_form.html', {'new_or_edit': 'New'})
    # return HttpResponse("nope")

def book_update(request, book_id):
    book = get_book(book_id)
    form = BookForm(request.POST or None, instance=book)
    if request.POST:
        # form = BookForm(request.POST, instance = book)
        if form.is_valid():
            form.save()
            return redirect('books:book_list')
    return render(request, 'books/book_form.html', {'form': form, 'new_or_edit': 'Edit'})

    # try:   
    #     book = Book.objects.get(pk=book_id)  
    
    #     if request.POST:
    #         try:
    #             book.title = request.POST["title"]
    #             book.author = request.POST["author"]
    #             book.pages = request.POST["pages"]
    #             book.full_clean()
    #             book.save()
    #             return redirect('books:book_list')
    #         except:
    #             return HttpResponse("You encountered an error!")

    #     return render(request, 'books/book_form.html', {'new_or_edit': 'Edit', "book" : book })
    
    # except:
    #     return HttpResponse("You encountered an error!")

    # return HttpResponse("nope")

def book_delete(request, book_id):
    book = get_book(book_id)
    if request.method=='POST':
        book.delete()
        return redirect('books:book_list')
    return render(request, 'books/book_confirm_delete.html', {'object':book})

library/books/templates/books/book_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Book Delete</h1>
<form method="post">{% csrf_token %}
  Are you sure you want to delete "{{ object.title }}" ?
  <input type="submit" value="Submit" />
  
</form>
</body>
</html>

library/books/templates/books/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Book Details</h1>
<h2>Title: {{ book.title }}</h2>
<h3> Author: {{ book.author}}</h3>
<p>Pages: {{ book.pages }}</p>
<hr/>
<a href="{% url 'books:book_list' %}">Back</a>
</body>
</html>

library/books/templates/books/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!-- <h1>Book Form: {{ new_or_edit }}</h1>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form> -->




<h1>Book Form: {{ new_or_edit }}</h1>
<form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
   

    <!-- {% if book %}
    <label> Title:</label>
    <input type="text" name="title" placeholder="title"  value="{{ book.title }}"/>
    <br />
    <label>Author:</label>
    <input type="text" name="author" placeholder="author" value="{{ book.author }}"/>
    <br />
    <label>Pages:</label>
    <input type="text" name="pages" placeholder="pages" value="{{ book.pages }}"/>
    <br />
    {% else %}
    <label>Title:</label>
    <input type="text" name="title" placeholder="title"/>
    <br />
    <label>Author:</label>
    <input type="text" name="author" placeholder="author"/>
    <br />
    <label>Pages:</label>
    <input type= "text" name="pages" placeholder="pages"/>
    <br />
    {% endif %} -->

    <input type="submit" value="Submit" />
</form>



<br />
</body>
</html>

library/books/templates/books/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel ='stylesheet' type='text/css' href='style.css'></link>
  <script src ='script.js' async defer></script>
  <title>My HTML Page</title>
</head>
<body>
  <nav id="body-nav"></nav>
  
  <main id = 'body-main'>
    <h1>Books</h1>

    <table border="1">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Pages</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for book in all_books %}
          <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.pages }}</td>
            <td><a href="{% url 'books:book_view' book.id %}">view</a></td>
            <td><a href="{% url 'books:book_edit' book.id %}">edit</a></td>
            <td><a href="{% url 'books:book_delete' book.id %}">delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <a href="{% url 'books:book_new' %}">New</a>
<footer id='body-footer'>

</footer>
</main>
</body>
</html>